# Generated by Django 5.1 on 2024-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cookbookcategory_cookbook_ingredient_preparationstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='cookbookcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
