# Generated by Django 5.1 on 2024-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='specification',
        ),
        migrations.AddField(
            model_name='specification',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
