# Generated by Django 5.1 on 2024-09-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_specification_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bowl_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooktop_compatibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dinner_plate_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dishwasher_safe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='idli_per_plate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='made_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_plates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pre_seasoned',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='snack_rice_plate_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spoon_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
