# Generated by Django 5.1 on 2024-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_best_seller_product_new_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amazon_buy_link',
            new_name='buy_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='blinkIt_buy_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flipkart_buy_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zepto_buy_link',
        ),
    ]
