# Generated by Django 5.1 on 2024-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_amazon_buy_link_product_buy_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
