# Generated by Django 5.1 on 2024-09-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_heroimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='heroimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
