# Generated by Django 5.1 on 2024-09-21 18:41

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_heroimage_options_heroimage_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='infographics/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='infographics',
            field=models.ManyToManyField(blank=True, to='api.productinfographic'),
        ),
    ]
