# Generated by Django 5.1 on 2024-09-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_productinfographic_product_infographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramphoto',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_1', to='api.collection')),
                ('collection_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_2', to='api.collection')),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
