# Generated by Django 5.1 on 2024-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_instagramphoto_options_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_images',
            field=models.ManyToManyField(blank=True, to='api.heroimage'),
        ),
    ]
