# Generated by Django 5.1 on 2024-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_homepagesettings_hero_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
