# Generated by Django 5.1.2 on 2024-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_heroimage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfeature',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='usageinstruction',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
